/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Jailton.Dayvid
 */
public class TeladeListagens extends javax.swing.JInternalFrame {

    /**
     * Creates new form TeladeListagens
     */
    public TeladeListagens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBoxFuncionario = new javax.swing.JCheckBox();
        jCheckBoxAluno = new javax.swing.JCheckBox();
        jCheckBoxVisitantes = new javax.swing.JCheckBox();
        jCheckBoxProfessor = new javax.swing.JCheckBox();
        jButtonTelaListagemImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Listagens");

        buttonGroup1.add(jCheckBoxFuncionario);
        jCheckBoxFuncionario.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jCheckBoxFuncionario.setText("Funcionários");

        buttonGroup1.add(jCheckBoxAluno);
        jCheckBoxAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jCheckBoxAluno.setText("Alunos");

        buttonGroup1.add(jCheckBoxVisitantes);
        jCheckBoxVisitantes.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jCheckBoxVisitantes.setText("Visitantes");

        buttonGroup1.add(jCheckBoxProfessor);
        jCheckBoxProfessor.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jCheckBoxProfessor.setText("Professor");

        jButtonTelaListagemImprimir.setBackground(new java.awt.Color(0, 0, 255));
        jButtonTelaListagemImprimir.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jButtonTelaListagemImprimir.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxFuncionario)
                .addGap(42, 42, 42)
                .addComponent(jCheckBoxAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jCheckBoxVisitantes)
                .addGap(47, 47, 47)
                .addComponent(jCheckBoxProfessor)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTelaListagemImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFuncionario)
                    .addComponent(jCheckBoxAluno)
                    .addComponent(jCheckBoxVisitantes)
                    .addComponent(jCheckBoxProfessor))
                .addGap(40, 40, 40)
                .addComponent(jButtonTelaListagemImprimir)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setBounds(30, 10, 597, 197);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonTelaListagemImprimir;
    private javax.swing.JCheckBox jCheckBoxAluno;
    private javax.swing.JCheckBox jCheckBoxFuncionario;
    private javax.swing.JCheckBox jCheckBoxProfessor;
    private javax.swing.JCheckBox jCheckBoxVisitantes;
    // End of variables declaration//GEN-END:variables
}
