/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import DTO.AlunosDTO;
import DAO.AlunoDAOConsulta;
import com.mysql.cj.xdevapi.Table;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Jailton.Dayvid
 */
public class TelaConsultaAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultaAluno
     */
    public TelaConsultaAluno() {
        initComponents();
        
      DefaultTableModel modelo = (DefaultTableModel) jTableTCAluno.getModel(); // Método para ordenar a tabela
      jTableTCAluno.setRowSorter(new TableRowSorter(modelo));
    }

       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jctipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtarg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTCAluno = new javax.swing.JTable();
        Jbca_Capturar = new javax.swing.JButton();
        Jbca_ImprimirFichas = new javax.swing.JButton();
        Jbca_Sair = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consulta de Alunos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jctipo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selicione:", "Id", "Nome", "CPF", "Status" }));

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel1.setText("Consulta por");

        jtarg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtargKeyReleased(evt);
            }
        });

        jLabel2.setText("Digite o Argumento:");

        jTableTCAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Nome", "CPF", "Dt Nascimento", "Telefone", "Status", "Multa"
            }
        ));
        jScrollPane1.setViewportView(jTableTCAluno);

        Jbca_Capturar.setBackground(new java.awt.Color(0, 0, 255));
        Jbca_Capturar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        Jbca_Capturar.setText("Pesquisar");
        Jbca_Capturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbca_CapturarActionPerformed(evt);
            }
        });

        Jbca_ImprimirFichas.setBackground(new java.awt.Color(0, 255, 51));
        Jbca_ImprimirFichas.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        Jbca_ImprimirFichas.setText("Imprimir Fichas");

        Jbca_Sair.setBackground(new java.awt.Color(255, 0, 0));
        Jbca_Sair.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        Jbca_Sair.setText("Sair");
        Jbca_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbca_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jbca_Capturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jbca_ImprimirFichas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jbca_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtarg, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtarg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jbca_Capturar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(Jbca_ImprimirFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(Jbca_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        setBounds(100, 50, 1317, 571);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       
        listarAlunos();
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void Jbca_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbca_SairActionPerformed

        dispose();

    }//GEN-LAST:event_Jbca_SairActionPerformed

    private void jtargKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtargKeyReleased
       
       
        
        
    }//GEN-LAST:event_jtargKeyReleased

    private void Jbca_CapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbca_CapturarActionPerformed
        
        String tipo= "";
         String escolha= jctipo.getSelectedItem().toString().trim();
         if(escolha.equals("Nome")){ // argumento selecionado vai filtrar e puxar as informaçações
             tipo= " "+"al_nome";
         }
         if(escolha.equals("CPF")){
             tipo=" "+"al_cpf";
         }
         if(escolha.equals("Id")){
             tipo=" "+"id_aluno";
         }
         if(escolha.equals("Status")){
             tipo=" "+"al_situacao";
        }
         
         if(escolha.equals("Multa")){
             tipo=" "+"al_multa";
        }
        
        
         
        String arg = jtarg.getText();
        
        DefaultTableModel mp1 = (DefaultTableModel) jTableTCAluno.getModel();
        int l=mp1.getRowCount();
        
        if(l>0){
            while(l>0){
                ((DefaultTableModel) jTableTCAluno.getModel()).removeRow(l-1);
                l--;
            } // fim do while
        } // FIM DO IF
        
        try {
            
            ResultSet rs = AlunoDAOConsulta.carregaTabelaAluno(tipo, arg);
            
            DefaultTableModel model = (DefaultTableModel) jTableTCAluno.getModel();
            
            
            while(rs.next()){
                String Coluna0=rs.getString("id_aluno");
                String Coluna1=rs.getString("al_nome").toString().trim();
                String Coluna2=rs.getString("al_cpf").toString().trim();
                String Coluna3=rs.getString("al_datanascimento").toString().trim();
                String Coluna4=rs.getString("al_telefone").toString().trim();
                String Coluna5=rs.getString("al_situacao").toString().trim();
                String Coluna6=rs.getString("al_multa").toString().trim();
                
              mp1.addRow(new String[] {Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5, Coluna6});
                
                
                
            }    
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro"+erro);
        }
        
        
        tamanhocolunas();
        jTableTCAluno.setAutoCreateRowSorter(true);
        
        
        
        
    }//GEN-LAST:event_Jbca_CapturarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbca_Capturar;
    private javax.swing.JButton Jbca_ImprimirFichas;
    private javax.swing.JButton Jbca_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTCAluno;
    private javax.swing.JComboBox<String> jctipo;
    private javax.swing.JTextField jtarg;
    // End of variables declaration//GEN-END:variables

  private void listarAlunos(){
      
      try {
          
          AlunoDAOConsulta objAlunoConsulta = new AlunoDAOConsulta();
          DefaultTableModel model = (DefaultTableModel) jTableTCAluno.getModel();
          model.setNumRows(0);
          
          ArrayList<AlunosDTO> lista = objAlunoConsulta.PesquisarAlunos();
          
          for(int num=0; num<lista.size(); num++){
              model.addRow(new Object[]{
                  
                  lista.get(num).getId_aluno(),
                  lista.get(num).getNome(),
                  lista.get(num).getCpf(),
                  lista.get(num).getDataNascimento(),
                  lista.get(num).getTelefone(),
                  lista.get(num).getSituacao(),
                  lista.get(num).getMulta()    
              });
              
          }
          
          
      } catch (Exception erro){
          JOptionPane.showMessageDialog(this, "Listar Alunos"+erro);
      }
      
  } // fim do metodo listar alunos
  
  
  public void tamanhocolunas(){
      
      jTableTCAluno.getColumnModel().getColumn(0).setMinWidth(100);
      jTableTCAluno.getColumnModel().getColumn(1).setMinWidth(250);
    
}

}


