/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import DAO.ProfessorDAO;
import DAO.ProfessorDAOExcluir;
import DTO.ProfessoresDTO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jailton.Dayvid
 */
public class TelaCadastroProfessor extends javax.swing.JInternalFrame {

    int acao;
    ProfessoresDTO objProfessorDTO = new ProfessoresDTO(0, null, null, null, null, null, null, null, null, 0, 0);
    ProfessorDAOExcluir objProfessorExcluir;

    public TelaCadastroProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTF_NomeProf = new javax.swing.JTextField();
        jTF_CodProf = new javax.swing.JTextField();
        jFTF_DataNascProf = new javax.swing.JFormattedTextField();
        jComboBoxSexoProf = new javax.swing.JComboBox<>();
        jFTF_CPFProf = new javax.swing.JFormattedTextField();
        jFTF_TelefoneProf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTF_EnderecoProf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFTF_salarioProf = new javax.swing.JFormattedTextField();
        jComboBoxFuncaoProf = new javax.swing.JComboBox<>();
        jComboBoxTurnoProf = new javax.swing.JComboBox<>();
        jFTF_HorasTrabProf = new javax.swing.JFormattedTextField();
        jButtonNovoProf = new javax.swing.JButton();
        jButtonCancelarProf = new javax.swing.JButton();
        jButtonEditarProf = new javax.swing.JButton();
        jButtonExcluirProf = new javax.swing.JButton();
        jButtonSalvarProf = new javax.swing.JButton();
        jButtonSairProf = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Professores");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel3.setText("Data de Nascimento:");

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel4.setText("Sexo:");

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel5.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel6.setText("Contato:");

        jTF_NomeProf.setEnabled(false);
        jTF_NomeProf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_NomeProfKeyReleased(evt);
            }
        });

        try {
            jFTF_DataNascProf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_DataNascProf.setEnabled(false);

        jComboBoxSexoProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Masculino", "Feminino" }));
        jComboBoxSexoProf.setEnabled(false);

        try {
            jFTF_CPFProf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_CPFProf.setEnabled(false);

        try {
            jFTF_TelefoneProf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_TelefoneProf.setEnabled(false);

        jLabel7.setText("Endereço:");

        jTF_EnderecoProf.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_CodProf, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTF_NomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jFTF_DataNascProf, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(260, 260, 260))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboBoxSexoProf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(135, 135, 135))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jFTF_CPFProf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFTF_TelefoneProf, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTF_EnderecoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_CodProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_NomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTF_DataNascProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTF_CPFProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTF_TelefoneProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTF_EnderecoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Contratação"));
        jPanel3.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel8.setText("Salário:");

        jLabel9.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel9.setText("Função:");

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel10.setText("Horas Trabalhadas:");

        jLabel11.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel11.setText("Turno:");

        try {
            jFTF_salarioProf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_salarioProf.setEnabled(false);

        jComboBoxFuncaoProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Professor Educação Física", "Personal", "Professor Dança", "Professor Artes Maciais" }));
        jComboBoxFuncaoProf.setEnabled(false);

        jComboBoxTurnoProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Manhã - Tarde", "Tarde - Noite", " " }));
        jComboBoxTurnoProf.setEnabled(false);

        try {
            jFTF_HorasTrabProf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jFTF_salarioProf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxFuncaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(220, 220, 220)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFTF_HorasTrabProf))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxTurnoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFTF_salarioProf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFuncaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTurnoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jFTF_HorasTrabProf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jButtonNovoProf.setBackground(new java.awt.Color(0, 0, 255));
        jButtonNovoProf.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButtonNovoProf.setText("Novo");
        jButtonNovoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoProfActionPerformed(evt);
            }
        });

        jButtonCancelarProf.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCancelarProf.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButtonCancelarProf.setText("Cancelar");
        jButtonCancelarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProfActionPerformed(evt);
            }
        });

        jButtonEditarProf.setBackground(new java.awt.Color(0, 255, 51));
        jButtonEditarProf.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButtonEditarProf.setText("Editar");
        jButtonEditarProf.setEnabled(false);
        jButtonEditarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProfActionPerformed(evt);
            }
        });

        jButtonExcluirProf.setBackground(new java.awt.Color(204, 204, 204));
        jButtonExcluirProf.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButtonExcluirProf.setText("Excluir");
        jButtonExcluirProf.setEnabled(false);
        jButtonExcluirProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProfActionPerformed(evt);
            }
        });

        jButtonSalvarProf.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalvarProf.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButtonSalvarProf.setText("Salvar");
        jButtonSalvarProf.setEnabled(false);
        jButtonSalvarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarProfActionPerformed(evt);
            }
        });

        jButtonSairProf.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSairProf.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButtonSairProf.setText("Sair");
        jButtonSairProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCancelarProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jButtonExcluirProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jButtonEditarProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalvarProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSairProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 302, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEditarProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvarProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSairProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExcluirProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelarProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(230, 25, 1083, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairProfActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairProfActionPerformed

    private void jButtonNovoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoProfActionPerformed
        // Metodo para ativar botão Novo
        acao = 1;
        botaonovoprofessor();
    }//GEN-LAST:event_jButtonNovoProfActionPerformed

    private void jButtonCancelarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProfActionPerformed
        // Metodo para ativar botão Salvar
        botaocancelarprofessor();
    }//GEN-LAST:event_jButtonCancelarProfActionPerformed

    private void jButtonEditarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProfActionPerformed
        // Metodo para ativar botão Editar
        acao = 2;
        botaoeditarprofessor();
    }//GEN-LAST:event_jButtonEditarProfActionPerformed

    private void jButtonSalvarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarProfActionPerformed
        regrasDeCampos();
    }//GEN-LAST:event_jButtonSalvarProfActionPerformed

    private void jButtonExcluirProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProfActionPerformed
        excluirProfessor();
    }//GEN-LAST:event_jButtonExcluirProfActionPerformed

    private void jTF_NomeProfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_NomeProfKeyReleased
        jTF_NomeProf.setText(jTF_NomeProf.getText().replaceAll("[^a-z | ^A-Z]", ""));
    }//GEN-LAST:event_jTF_NomeProfKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jFTF_HorasTrabProf.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarProf;
    private javax.swing.JButton jButtonEditarProf;
    private javax.swing.JButton jButtonExcluirProf;
    private javax.swing.JButton jButtonNovoProf;
    private javax.swing.JButton jButtonSairProf;
    private javax.swing.JButton jButtonSalvarProf;
    private javax.swing.JComboBox<String> jComboBoxFuncaoProf;
    private javax.swing.JComboBox<String> jComboBoxSexoProf;
    private javax.swing.JComboBox<String> jComboBoxTurnoProf;
    private javax.swing.JFormattedTextField jFTF_CPFProf;
    private javax.swing.JFormattedTextField jFTF_DataNascProf;
    private javax.swing.JFormattedTextField jFTF_HorasTrabProf;
    private javax.swing.JFormattedTextField jFTF_TelefoneProf;
    private javax.swing.JFormattedTextField jFTF_salarioProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_CodProf;
    private javax.swing.JTextField jTF_EnderecoProf;
    private javax.swing.JTextField jTF_NomeProf;
    // End of variables declaration//GEN-END:variables

    public void botaonovoprofessor() {

        jTF_CodProf.setEnabled(false);
        jTF_NomeProf.setEnabled(true);
        jFTF_DataNascProf.setEnabled(true);

        jFTF_CPFProf.setEnabled(true);
        jFTF_TelefoneProf.setEnabled(true);
        jTF_EnderecoProf.setEnabled(true);
        jFTF_salarioProf.setEnabled(true);
        jFTF_HorasTrabProf.setEnabled(true);

        jComboBoxSexoProf.setEnabled(true);
        jComboBoxFuncaoProf.setEnabled(true);
        jComboBoxTurnoProf.setEnabled(true);

        jButtonEditarProf.setEnabled(true);
        jButtonSalvarProf.setEnabled(true);
        jButtonCancelarProf.setEnabled(true);

        jTF_CodProf.setText("");
        jTF_NomeProf.setText("");
        jFTF_DataNascProf.setText("");
        jFTF_CPFProf.setText("");
        jFTF_TelefoneProf.setText("");
        jTF_EnderecoProf.setText("");
        jFTF_salarioProf.setText("");
        jFTF_HorasTrabProf.setText("");

    } // fim do metodo Botão_Novo_Professor!!

    public void botaocancelarprofessor() {

        jTF_CodProf.setText("");
        jTF_NomeProf.setText("");
        jFTF_DataNascProf.setText("");
        jFTF_CPFProf.setText("");
        jFTF_TelefoneProf.setText("");
        jTF_EnderecoProf.setText("");
        jFTF_salarioProf.setText("");
        jFTF_HorasTrabProf.setText("");

        jTF_CodProf.setEnabled(true);
        jTF_NomeProf.setEnabled(false);
        jFTF_DataNascProf.setEnabled(false);
        jFTF_CPFProf.setEnabled(false);
        jFTF_TelefoneProf.setEnabled(false);
        jTF_EnderecoProf.setEnabled(false);
        jFTF_salarioProf.setEnabled(false);
        jFTF_HorasTrabProf.setEnabled(false);

        jComboBoxSexoProf.setEnabled(false);
        jComboBoxFuncaoProf.setEnabled(false);
        jComboBoxTurnoProf.setEnabled(false);

        jButtonEditarProf.setEnabled(false);
        jButtonSalvarProf.setEnabled(false);
        jButtonCancelarProf.setEnabled(false);
        jButtonExcluirProf.setEnabled(false);

    } // fim do metodo Botão_Cancelar_Professor!!

    public void botaoeditarprofessor() {

        jTF_CodProf.setEnabled(false);
        jTF_NomeProf.setEnabled(true);
        jFTF_DataNascProf.setEnabled(true);
        jFTF_CPFProf.setEnabled(true);
        jFTF_TelefoneProf.setEnabled(true);
        jTF_EnderecoProf.setEnabled(true);
        jFTF_salarioProf.setEnabled(true);
        jFTF_HorasTrabProf.setEnabled(true);

        jComboBoxSexoProf.setEnabled(true);
        jComboBoxFuncaoProf.setEnabled(true);
        jComboBoxTurnoProf.setEnabled(true);

        jButtonEditarProf.setEnabled(true);
        jButtonSalvarProf.setEnabled(true);
        jButtonCancelarProf.setEnabled(true);
        jButtonExcluirProf.setEnabled(true);

    } // fim do metodo Botão_Editar_Professor!!

    private int toFloat(float salario) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private float toString(float salario) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void regrasDeCampos() {

        if (jTF_NomeProf.getText().isEmpty()) { // codigo para verificar se o campo ta vazio

            JOptionPane.showMessageDialog(null, "Campo Nome obrigatorio");
            jTF_NomeProf.requestFocus(); // voltar para o campo nome para usuario preencher

        } else if (jFTF_DataNascProf.getText().equals("  /  /    ")) {

            JOptionPane.showMessageDialog(null, "Campo Data de Nascimento obrigatorio");
            jFTF_DataNascProf.requestFocus();

        } else if (jComboBoxSexoProf.getSelectedItem().equals("Selecione:")) {

            JOptionPane.showMessageDialog(null, "Selecione seu genero");
            jComboBoxSexoProf.requestFocus();

        } else if (jFTF_CPFProf.getText().equals("   .   .   -  ")) {

            JOptionPane.showMessageDialog(null, "Campo CPF obrigatorio");
            jFTF_CPFProf.requestFocus();

        } else if (jFTF_TelefoneProf.getText().equals("(  )     -    ")) {

            JOptionPane.showMessageDialog(null, "Campo Contato obrigatorio");
            jFTF_TelefoneProf.requestFocus();

        } else if (jTF_EnderecoProf.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Campo Endereço obrigatorio");
            jTF_EnderecoProf.requestFocus();

        } else if (jFTF_salarioProf.getText().equals("    .  ")) {

            JOptionPane.showMessageDialog(null, "Campo saláro obrigatorio");
            jFTF_salarioProf.requestFocus();

        } else if (jComboBoxFuncaoProf.getSelectedItem().equals("Selecione:")) {

            JOptionPane.showMessageDialog(null, "Selecione a função do professor");
            jComboBoxFuncaoProf.requestFocus();

        } else if (jFTF_HorasTrabProf.getText().equals("  ")) { // codigo para verificar se o campo ta vazio

            JOptionPane.showMessageDialog(null, "Campo horas trabalhada obrigatorio");
            jFTF_HorasTrabProf.requestFocus(); // voltar para o campo nome para usuario preencher

        } else if (jComboBoxTurnoProf.getSelectedItem().equals("Selecione:")) {

            JOptionPane.showMessageDialog(null, "Selecione o turno do professor");
            jComboBoxTurnoProf.requestFocus();
        } else {
            validarDate();
        }

    } // FIM DO METODO REGRAS DE CAMPO

    public void validarDate() {

        // PROCESSO PARA VALIDAR CAMPO
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();

        Date dataNascimento;
        try {
            dataNascimento = sdf.parse(jFTF_DataNascProf.getText());

            cal.setTime(dataNascimento);
            cal.add(Calendar.MONTH, 2);

            int year = cal.get(Calendar.YEAR);
            dataNascimento = cal.getTime();

            Date atualData = new Date();
            cal.setTime(atualData);

            int atualYear = cal.get(Calendar.YEAR);
            int idade = atualYear - year;

            if (idade < 16) {

                JOptionPane.showMessageDialog(null, "Idade minima para ser Professor é de 16 anos");
                jFTF_DataNascProf.requestFocus();

            } else {
                salvarProfessor();

            }
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }

    } // FIM DO METODO VALIDAR DATA

    public void salvarProfessor() {

        int cod;

        objProfessorDTO = new ProfessoresDTO(0, null, null, null, null, null, null, null, null, 0, 0);
        /*
        String tmpstr = jFTF_salarioProf.getText();
        tmpstr = tmpstr.replaceAll("R$", "");
        //tmpstr = tmpstr.replaceAll(".", "");
         */
        objProfessorDTO.setNome(jTF_NomeProf.getText());
        objProfessorDTO.setDataNascimento(jFTF_DataNascProf.getText());
        objProfessorDTO.setSexo((String) jComboBoxSexoProf.getSelectedItem());
        objProfessorDTO.setCpf(jFTF_CPFProf.getText());
        objProfessorDTO.setTelefone(jFTF_TelefoneProf.getText());
        objProfessorDTO.setEnd(jTF_EnderecoProf.getText());
        objProfessorDTO.setSalario(Float.parseFloat(jFTF_salarioProf.getText()));
        objProfessorDTO.setFuncao((String) jComboBoxFuncaoProf.getSelectedItem());
        objProfessorDTO.setHorasTrab((Integer.parseInt(jFTF_HorasTrabProf.getText())));
        objProfessorDTO.setTurno((String) jComboBoxTurnoProf.getSelectedItem());

        try {
            ProfessorDAO objProfessorDAO = new ProfessorDAO();

            if (acao == 1) {

                cod = objProfessorDAO.Professor(objProfessorDTO);
                jTF_CodProf.setText(String.valueOf(cod));
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");

                jTF_CodProf.setEnabled(true);
                jTF_NomeProf.setEnabled(false);
                jFTF_DataNascProf.setEnabled(false);
                jFTF_CPFProf.setEnabled(false);
                jFTF_TelefoneProf.setEnabled(false);
                jTF_EnderecoProf.setEnabled(false);
                jFTF_salarioProf.setEnabled(false);
                jFTF_HorasTrabProf.setEnabled(false);

                jComboBoxSexoProf.setEnabled(false);
                jComboBoxFuncaoProf.setEnabled(false);
                jComboBoxTurnoProf.setEnabled(false);

                jButtonEditarProf.setEnabled(true);
                jButtonSalvarProf.setEnabled(false);
                jButtonCancelarProf.setEnabled(false);

            }

            if (acao == 2) {

                objProfessorDTO.setId_professor(Integer.parseInt(jTF_CodProf.getText()));
                if (objProfessorDAO.EditarProfessor(objProfessorDTO)) {

                    JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                    jTF_CodProf.setEnabled(true);
                    jTF_NomeProf.setEnabled(false);
                    jFTF_DataNascProf.setEnabled(false);
                    jFTF_CPFProf.setEnabled(false);
                    jFTF_TelefoneProf.setEnabled(false);
                    jTF_EnderecoProf.setEnabled(false);
                    jFTF_salarioProf.setEnabled(false);
                    jFTF_HorasTrabProf.setEnabled(false);

                    jComboBoxSexoProf.setEnabled(false);
                    jComboBoxFuncaoProf.setEnabled(false);
                    jComboBoxTurnoProf.setEnabled(false);

                    jButtonEditarProf.setEnabled(true);
                    jButtonSalvarProf.setEnabled(false);
                    jButtonCancelarProf.setEnabled(false);

                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Operação deu erro" + e.getMessage());
        }

    } // FIM DO METODO SALVAR PROFESSOR

    public void excluirProfessor() {

        if (jTF_CodProf.getText().equals("")) {  //  ESSE IF VAI SER PARA FAZER UMA VERIFICAÇÃO, SE TEM CODIGO OU NÃO..

            JOptionPane.showMessageDialog(this, "Digite o Código");

        } else { // SE TIVER CODIGO VAI FAZER A SEGUINTE OPERAÇÃO

            int codigo = Integer.parseInt(jTF_CodProf.getText());  // ESSA VARIVEL VAI CARREGAR OS VALORES DO CAMPO CITADO.
            objProfessorExcluir = new ProfessorDAOExcluir(); // codigo para instanciar o objeto

            try {

                if (JOptionPane.showConfirmDialog(this, "Confirma a exclusão do Professor?", "Confirmação",
                        JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) { // codigo para da 3 opções ao usuario, sim, não e cancelar
                    // codigo a cima vai ser muito utilizado para perguntar algo ao usuario
                    if (objProfessorExcluir.ExcluirProfessor(codigo)) { // se a caixa for respondida com sim, ele vai retornar a mensagem a baixo e executar.
                        JOptionPane.showMessageDialog(this, "Professor Excluido com sucesso !");
                        botaocancelarprofessor();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir o registro");
                    }
                } else {

                    JOptionPane.showMessageDialog(this, "Operação Cancelada !");
                    botaocancelarprofessor();

                }

            } catch (SQLException erro) {
                JOptionPane.showMessageDialog(this, "Erro: Exclusão de Professor Não Realizada" + erro.getMessage());
            }

        }

    } // FIM DO METODO EXCLUIR PROFESSOR

}// fim da classe principal
