/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Jailton.Dayvid
 */
public class TelaCadastroUsuario extends javax.swing.JInternalFrame {

  
    
    public TelaCadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_Nome_C_user = new javax.swing.JTextField();
        jPasswoFSenhaUser = new javax.swing.JPasswordField();
        jPasswoFCSenhaUser = new javax.swing.JPasswordField();
        jButton_TC_User_Cancelar = new javax.swing.JButton();
        jButton_TC_User_Editar = new javax.swing.JButton();
        jButton_TC_User_Salvar = new javax.swing.JButton();
        jButton_TC_User_Novo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Usuários");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Cadastre seu Usuário:");

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Digite sua Senha:");

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Confirme novamente sua Senha:");

        jTF_Nome_C_user.setEnabled(false);

        jPasswoFSenhaUser.setEnabled(false);

        jPasswoFCSenhaUser.setEnabled(false);

        jButton_TC_User_Cancelar.setBackground(new java.awt.Color(255, 0, 0));
        jButton_TC_User_Cancelar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButton_TC_User_Cancelar.setText("Cancelar");
        jButton_TC_User_Cancelar.setEnabled(false);
        jButton_TC_User_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TC_User_CancelarActionPerformed(evt);
            }
        });

        jButton_TC_User_Editar.setBackground(new java.awt.Color(0, 204, 51));
        jButton_TC_User_Editar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButton_TC_User_Editar.setText("Editar Usuário");
        jButton_TC_User_Editar.setEnabled(false);
        jButton_TC_User_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TC_User_EditarActionPerformed(evt);
            }
        });

        jButton_TC_User_Salvar.setBackground(new java.awt.Color(204, 204, 255));
        jButton_TC_User_Salvar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButton_TC_User_Salvar.setText("Salvar Usuário");
        jButton_TC_User_Salvar.setEnabled(false);
        jButton_TC_User_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TC_User_SalvarActionPerformed(evt);
            }
        });

        jButton_TC_User_Novo.setBackground(new java.awt.Color(0, 0, 255));
        jButton_TC_User_Novo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButton_TC_User_Novo.setText("Novo Usuário");
        jButton_TC_User_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TC_User_NovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_Nome_C_user)
                    .addComponent(jPasswoFSenhaUser)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(jPasswoFCSenhaUser)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_TC_User_Cancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_TC_User_Salvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_TC_User_Editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_TC_User_Novo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF_Nome_C_user, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswoFSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPasswoFCSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton_TC_User_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_TC_User_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_TC_User_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_TC_User_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(30, 10, 1303, 730);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton_TC_User_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TC_User_EditarActionPerformed
         // Metodo para ativar botão Editar Usuário
        BotaoEditarUsuario();
    }//GEN-LAST:event_jButton_TC_User_EditarActionPerformed

    private void jButton_TC_User_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TC_User_SalvarActionPerformed

        BotaoSalvarUsuario();
    }//GEN-LAST:event_jButton_TC_User_SalvarActionPerformed

    private void jButton_TC_User_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TC_User_CancelarActionPerformed
        // Metodo para ativar botão Cancelar Usuário
       
        BotaoCancelarUsuario();
    }//GEN-LAST:event_jButton_TC_User_CancelarActionPerformed

    private void jButton_TC_User_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TC_User_NovoActionPerformed
        // Metodo para ativar botão Novo Usuário
       
        BotaoNovoUsuario();
    }//GEN-LAST:event_jButton_TC_User_NovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_TC_User_Cancelar;
    private javax.swing.JButton jButton_TC_User_Editar;
    private javax.swing.JButton jButton_TC_User_Novo;
    private javax.swing.JButton jButton_TC_User_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswoFCSenhaUser;
    private javax.swing.JPasswordField jPasswoFSenhaUser;
    private javax.swing.JTextField jTF_Nome_C_user;
    // End of variables declaration//GEN-END:variables


 public void BotaoNovoUsuario(){
   
    
    jTF_Nome_C_user.setEnabled(true);
    jPasswoFSenhaUser.setEnabled(true);
    jPasswoFCSenhaUser.setEnabled(true);
     
    jButton_TC_User_Editar.setEnabled(true);
    jButton_TC_User_Cancelar.setEnabled(true);
    jButton_TC_User_Salvar.setEnabled(true);
    
    jTF_Nome_C_user.setText("");
    jPasswoFSenhaUser.setText("");
    jPasswoFCSenhaUser.setText("");
        
    } // fim do metodo Novo Usuário!!

 public void BotaoEditarUsuario(){
   
    
    jTF_Nome_C_user.setEnabled(true);
    jPasswoFSenhaUser.setEnabled(true);
    jPasswoFCSenhaUser.setEnabled(true);
     
    jButton_TC_User_Editar.setEnabled(true);
    jButton_TC_User_Cancelar.setEnabled(true);
    jButton_TC_User_Salvar.setEnabled(true);    
    
 } // fim do metodo Editar Usuário!!

public void BotaoCancelarUsuario() {
   
    jTF_Nome_C_user.setText("");
    jPasswoFSenhaUser.setText("");
    jPasswoFCSenhaUser.setText("");
    
    jTF_Nome_C_user.setEnabled(false);
    jPasswoFSenhaUser.setEnabled(false);
    jPasswoFCSenhaUser.setEnabled(false);
    
    jButton_TC_User_Novo.setEnabled(true);
    jButton_TC_User_Editar.setEnabled(false);
    jButton_TC_User_Cancelar.setEnabled(false);
    jButton_TC_User_Salvar.setEnabled(false);
    
} // fim do metodo Cancelar Usuário!!

public void BotaoSalvarUsuario() {
    
    jTF_Nome_C_user.setEnabled(false);
    jPasswoFSenhaUser.setEnabled(false);
    jPasswoFCSenhaUser.setEnabled(false);
     
    jButton_TC_User_Novo.setEnabled(false);
    jButton_TC_User_Editar.setEnabled(true);
    jButton_TC_User_Cancelar.setEnabled(false);
    
} // fim do metodo Salvar Usuário!!

}// fim da classe principal!!!
