/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jailton.Dayvid
 */
public class TelaCadastroPagamentosFinanceiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroPagamentosFinanceiro
     */
    public TelaCadastroPagamentosFinanceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox_Cadastro_Pagamento = new javax.swing.JLabel();
        jComboBox_Cadastro_Pagamento_Tipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTF_NomeCadastro_Cadastro_Pagamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTF_CPFCadastro_Cadastro_Pagamento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFTF__Valor_Cadastro_Pagamento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTF_Datapag_Cadastro_Pagamento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_Cadastro_Pagamento_Motivo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCadastroPagamento = new javax.swing.JTable();
        jButton_Cadastro_Pagamento_Novo = new javax.swing.JButton();
        jButton_Cadastro_Pagamento_Editar = new javax.swing.JButton();
        Cadastro_Pagamento_Salvar = new javax.swing.JButton();
        Cadastro_Pagamento_Excluir = new javax.swing.JButton();
        Cadastro_Pagamento_Cancelar = new javax.swing.JButton();
        Cadastro_Pagamento_Sair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jFTF_Datapag_Cadastro_Pagamento1 = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mensalidade e Pagamentos");

        jPanel1.setAlignmentX(40.0F);
        jPanel1.setAlignmentY(10.0F);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamentos"));

        jComboBox_Cadastro_Pagamento.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jComboBox_Cadastro_Pagamento.setText("Tipo de Cliente:");

        jComboBox_Cadastro_Pagamento_Tipo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jComboBox_Cadastro_Pagamento_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Aluno", "Visitantes", "Fornecedor", "Funcionários", "Professores" }));
        jComboBox_Cadastro_Pagamento_Tipo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel2.setText("Nome:");

        jTF_NomeCadastro_Cadastro_Pagamento.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel3.setText("CPF:");

        try {
            jFTF_CPFCadastro_Cadastro_Pagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_CPFCadastro_Cadastro_Pagamento.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel4.setText("Valor:");

        try {
            jFTF__Valor_Cadastro_Pagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF__Valor_Cadastro_Pagamento.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel5.setText("Data do Pagamento:");

        try {
            jFTF_Datapag_Cadastro_Pagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_Datapag_Cadastro_Pagamento.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel6.setText("Motivo");

        jComboBox_Cadastro_Pagamento_Motivo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jComboBox_Cadastro_Pagamento_Motivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Mensalidades", "Pagamento a Fornecedor", "Pagamentos a Professores", "Pagamentos a Funcionários", "Diversos" }));
        jComboBox_Cadastro_Pagamento_Motivo.setEnabled(false);

        jTableCadastroPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nome", "CPF", "Motivo", "Data Pagamento", "Valor", "Vencimento"
            }
        ));
        jScrollPane2.setViewportView(jTableCadastroPagamento);

        jButton_Cadastro_Pagamento_Novo.setBackground(new java.awt.Color(0, 0, 255));
        jButton_Cadastro_Pagamento_Novo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButton_Cadastro_Pagamento_Novo.setText("Novo Pagamento");
        jButton_Cadastro_Pagamento_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_Pagamento_NovoActionPerformed(evt);
            }
        });

        jButton_Cadastro_Pagamento_Editar.setBackground(new java.awt.Color(0, 255, 51));
        jButton_Cadastro_Pagamento_Editar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jButton_Cadastro_Pagamento_Editar.setText("Editar Pagamento");
        jButton_Cadastro_Pagamento_Editar.setEnabled(false);
        jButton_Cadastro_Pagamento_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_Pagamento_EditarActionPerformed(evt);
            }
        });

        Cadastro_Pagamento_Salvar.setBackground(new java.awt.Color(204, 204, 255));
        Cadastro_Pagamento_Salvar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        Cadastro_Pagamento_Salvar.setText("Salvar Pagamento");
        Cadastro_Pagamento_Salvar.setEnabled(false);
        Cadastro_Pagamento_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_Pagamento_SalvarActionPerformed(evt);
            }
        });

        Cadastro_Pagamento_Excluir.setBackground(new java.awt.Color(204, 204, 204));
        Cadastro_Pagamento_Excluir.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        Cadastro_Pagamento_Excluir.setText("Excluir Pagamento");
        Cadastro_Pagamento_Excluir.setEnabled(false);

        Cadastro_Pagamento_Cancelar.setBackground(new java.awt.Color(255, 0, 0));
        Cadastro_Pagamento_Cancelar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        Cadastro_Pagamento_Cancelar.setText("Cancelar Pagamento");
        Cadastro_Pagamento_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_Pagamento_CancelarActionPerformed(evt);
            }
        });

        Cadastro_Pagamento_Sair.setBackground(new java.awt.Color(204, 204, 204));
        Cadastro_Pagamento_Sair.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        Cadastro_Pagamento_Sair.setText("Sair");
        Cadastro_Pagamento_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_Pagamento_SairActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel7.setText("Próximo Vencimento:");

        try {
            jFTF_Datapag_Cadastro_Pagamento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_Datapag_Cadastro_Pagamento1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Cadastro_Pagamento_Tipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(jComboBox_Cadastro_Pagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_NomeCadastro_Cadastro_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jFTF_Datapag_Cadastro_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox_Cadastro_Pagamento_Motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(jFTF__Valor_Cadastro_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFTF_Datapag_Cadastro_Pagamento1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFTF_CPFCadastro_Cadastro_Pagamento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                            .addGap(1, 1, 1)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Cadastro_Pagamento_Novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cadastro_Pagamento_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Cadastro_Pagamento_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cadastro_Pagamento_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_Cadastro_Pagamento_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cadastro_Pagamento_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_Cadastro_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_Cadastro_Pagamento_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTF_NomeCadastro_Cadastro_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFTF_CPFCadastro_Cadastro_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFTF_Datapag_Cadastro_Pagamento1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jFTF_Datapag_Cadastro_Pagamento)
                        .addComponent(jComboBox_Cadastro_Pagamento_Motivo)
                        .addComponent(jFTF__Valor_Cadastro_Pagamento)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cadastro_Pagamento_Novo)
                    .addComponent(jButton_Cadastro_Pagamento_Editar)
                    .addComponent(Cadastro_Pagamento_Salvar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastro_Pagamento_Excluir)
                    .addComponent(Cadastro_Pagamento_Cancelar)
                    .addComponent(Cadastro_Pagamento_Sair))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );

        setBounds(30, 10, 1368, 722);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_Pagamento_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_Pagamento_SairActionPerformed
      this.dispose();
    }//GEN-LAST:event_Cadastro_Pagamento_SairActionPerformed

    private void jButton_Cadastro_Pagamento_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_Pagamento_NovoActionPerformed
        // Metodo para ativar botão Novo
        
        botaoCadastro_Pagamento_Novo();
        
    }//GEN-LAST:event_jButton_Cadastro_Pagamento_NovoActionPerformed

    private void Cadastro_Pagamento_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_Pagamento_CancelarActionPerformed
        // Metodo para ativar botão Cancelar
        
        botaoCadastro_Pagamento_Cancelar();
    }//GEN-LAST:event_Cadastro_Pagamento_CancelarActionPerformed

    private void jButton_Cadastro_Pagamento_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_Pagamento_EditarActionPerformed
        // Metodo para ativar botão Editar
        
        botaoCadastro_Pagamento_Editar();
    }//GEN-LAST:event_jButton_Cadastro_Pagamento_EditarActionPerformed

    private void Cadastro_Pagamento_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_Pagamento_SalvarActionPerformed
        // Metodo para ativar botão Salvar
               
        
        botaoCadastro_Pagamento_Salvar();
    }//GEN-LAST:event_Cadastro_Pagamento_SalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastro_Pagamento_Cancelar;
    private javax.swing.JButton Cadastro_Pagamento_Excluir;
    private javax.swing.JButton Cadastro_Pagamento_Sair;
    private javax.swing.JButton Cadastro_Pagamento_Salvar;
    private javax.swing.JButton jButton_Cadastro_Pagamento_Editar;
    private javax.swing.JButton jButton_Cadastro_Pagamento_Novo;
    private javax.swing.JLabel jComboBox_Cadastro_Pagamento;
    private javax.swing.JComboBox<String> jComboBox_Cadastro_Pagamento_Motivo;
    private javax.swing.JComboBox<String> jComboBox_Cadastro_Pagamento_Tipo;
    private javax.swing.JFormattedTextField jFTF_CPFCadastro_Cadastro_Pagamento;
    private javax.swing.JFormattedTextField jFTF_Datapag_Cadastro_Pagamento;
    private javax.swing.JFormattedTextField jFTF_Datapag_Cadastro_Pagamento1;
    private javax.swing.JFormattedTextField jFTF__Valor_Cadastro_Pagamento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF_NomeCadastro_Cadastro_Pagamento;
    private javax.swing.JTable jTableCadastroPagamento;
    // End of variables declaration//GEN-END:variables



public void botaoCadastro_Pagamento_Novo() {
  
    jComboBox_Cadastro_Pagamento_Tipo.setEnabled(true);
    jTF_NomeCadastro_Cadastro_Pagamento.setEnabled(true);
    jFTF_CPFCadastro_Cadastro_Pagamento.setEnabled(true);
    jComboBox_Cadastro_Pagamento_Motivo.setEnabled(true);
    jFTF_Datapag_Cadastro_Pagamento.setEnabled(true);
    jFTF__Valor_Cadastro_Pagamento.setEnabled(true);
    
    
    jButton_Cadastro_Pagamento_Editar.setEnabled(true);
    Cadastro_Pagamento_Salvar.setEnabled(true);
    Cadastro_Pagamento_Cancelar.setEnabled(true);
    
    
    jTF_NomeCadastro_Cadastro_Pagamento.setText("");
    jFTF_CPFCadastro_Cadastro_Pagamento.setText("");
    jFTF_Datapag_Cadastro_Pagamento.setText("");
    jFTF__Valor_Cadastro_Pagamento.setText("");
      
    
} // fim do metodo botaoCadastro_Pagamento_Novo!!


public void botaoCadastro_Pagamento_Cancelar(){
    
    jTF_NomeCadastro_Cadastro_Pagamento.setText("");
    jFTF_CPFCadastro_Cadastro_Pagamento.setText("");
    jFTF_Datapag_Cadastro_Pagamento.setText("");
    jFTF__Valor_Cadastro_Pagamento.setText("");
    
    
    jComboBox_Cadastro_Pagamento_Tipo.setEnabled(false);
    jTF_NomeCadastro_Cadastro_Pagamento.setEnabled(false);
    jFTF_CPFCadastro_Cadastro_Pagamento.setEnabled(false);
    jComboBox_Cadastro_Pagamento_Motivo.setEnabled(false);
    jFTF_Datapag_Cadastro_Pagamento.setEnabled(false);
    jFTF__Valor_Cadastro_Pagamento.setEnabled(false);
    
    
    jButton_Cadastro_Pagamento_Editar.setEnabled(false);
    Cadastro_Pagamento_Salvar.setEnabled(false);
    Cadastro_Pagamento_Cancelar.setEnabled(false);   
    
} // fim do metodo botaoCadastro_Pagamento_Cancelar!!


public void botaoCadastro_Pagamento_Editar() {
    
    jComboBox_Cadastro_Pagamento_Tipo.setEnabled(true);
    jTF_NomeCadastro_Cadastro_Pagamento.setEnabled(true);
    jFTF_CPFCadastro_Cadastro_Pagamento.setEnabled(true);
    jComboBox_Cadastro_Pagamento_Motivo.setEnabled(true);
    jFTF_Datapag_Cadastro_Pagamento.setEnabled(true);
    jFTF__Valor_Cadastro_Pagamento.setEnabled(true);
    
    
    jButton_Cadastro_Pagamento_Editar.setEnabled(true);
    Cadastro_Pagamento_Salvar.setEnabled(true);
    Cadastro_Pagamento_Cancelar.setEnabled(true); 
    Cadastro_Pagamento_Excluir.setEnabled(true);
    
} // fim do metodo botaoCadastro_Pagamento_Editar!!


public void botaoCadastro_Pagamento_Salvar() {
    
    jComboBox_Cadastro_Pagamento_Tipo.setEnabled(false);
    jTF_NomeCadastro_Cadastro_Pagamento.setEnabled(false);
    jFTF_CPFCadastro_Cadastro_Pagamento.setEnabled(false);
    jComboBox_Cadastro_Pagamento_Motivo.setEnabled(false);
    jFTF_Datapag_Cadastro_Pagamento.setEnabled(false);
    jFTF__Valor_Cadastro_Pagamento.setEnabled(false);
    
    
    jButton_Cadastro_Pagamento_Editar.setEnabled(true);
    Cadastro_Pagamento_Salvar.setEnabled(false);
    Cadastro_Pagamento_Cancelar.setEnabled(false); 
    
}// fim do metodo botaoCadastro_Pagamento_Salvar!!



}
