/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import DAO.VisitantesDAOConsulta;
import DTO.VisitantesDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jailton.Dayvid
 */
public class TelaConsultaVisitantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultaVisitantes
     */
    public TelaConsultaVisitantes() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableTCVisitantes.getModel();
        jTableTCVisitantes.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jctipo = new javax.swing.JComboBox<>();
        jtarg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTCVisitantes = new javax.swing.JTable();
        Jbcv_Capturar = new javax.swing.JButton();
        Jbcv_ImprimirFichas = new javax.swing.JButton();
        Jbcv_Sair = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela Consulta Visitantes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel1.setText("Consultar por:");

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel2.setText("Digite o Argumento:");

        jctipo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selicione:", "Id", "Nome", "CPF", " " }));

        jtarg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtargActionPerformed(evt);
            }
        });

        jTableTCVisitantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Nome", "CPF ", "Dt nascimento ", "Telefone ", "Valor diaria"
            }
        ));
        jScrollPane1.setViewportView(jTableTCVisitantes);

        Jbcv_Capturar.setBackground(new java.awt.Color(0, 0, 255));
        Jbcv_Capturar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        Jbcv_Capturar.setText("Pesquisar");
        Jbcv_Capturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbcv_CapturarActionPerformed(evt);
            }
        });

        Jbcv_ImprimirFichas.setBackground(new java.awt.Color(0, 255, 51));
        Jbcv_ImprimirFichas.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        Jbcv_ImprimirFichas.setText("Imprimir Fichas");

        Jbcv_Sair.setBackground(new java.awt.Color(255, 0, 0));
        Jbcv_Sair.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        Jbcv_Sair.setText("Sair");
        Jbcv_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbcv_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jbcv_Capturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jbcv_ImprimirFichas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jbcv_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jtarg, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jbcv_Capturar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(Jbcv_ImprimirFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(Jbcv_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtarg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );

        setBounds(100, 50, 1317, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void jtargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtargActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtargActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        listarAlunos();


    }//GEN-LAST:event_formInternalFrameOpened

    private void Jbcv_CapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbcv_CapturarActionPerformed
       
        
         String tipo= "";
         String escolha= jctipo.getSelectedItem().toString().trim();
         if(escolha.equals("Nome")){ // argumento selecionado vai filtrar e puxar as informaçações
             tipo= " "+"vis_nome";
         }
         if(escolha.equals("CPF")){
             tipo=" "+"vis_cpf";
         }
         if(escolha.equals("Id")){
             tipo=" "+"id_visitantes";
         }
         
        
         
        String arg = jtarg.getText();
        
        DefaultTableModel mp1 = (DefaultTableModel) jTableTCVisitantes.getModel();
        int l=mp1.getRowCount();
        
        if(l>0){
            while(l>0){
                ((DefaultTableModel) jTableTCVisitantes.getModel()).removeRow(l-1);
                l--;
            } // fim do while
        } // FIM DO IF
        
        try {
            
            ResultSet rs = VisitantesDAOConsulta.carregaTabelVisitantes(tipo, arg);
            
            DefaultTableModel model = (DefaultTableModel) jTableTCVisitantes.getModel();
            
            
            while(rs.next()){
                String Coluna0=rs.getString("id_visitantes");
                String Coluna1=rs.getString("vis_nome").toString().trim();
                String Coluna2=rs.getString("vis_cpf").toString().trim();
                String Coluna3=rs.getString("vis_datanascimento").toString().trim();
                String Coluna4=rs.getString("vis_telefone").toString().trim();
                String Coluna5=rs.getString("vis_valordiaria").toString().trim();
                
              mp1.addRow(new String[] {Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5});
                
                
                
            }    
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro"+erro);
        }
        
        
        tamanhocolunas();
        jTableTCVisitantes.setAutoCreateRowSorter(true);
        
        
        
        
        
        
    }//GEN-LAST:event_Jbcv_CapturarActionPerformed

    private void Jbcv_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbcv_SairActionPerformed
    dispose();
    }//GEN-LAST:event_Jbcv_SairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbcv_Capturar;
    private javax.swing.JButton Jbcv_ImprimirFichas;
    private javax.swing.JButton Jbcv_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTCVisitantes;
    private javax.swing.JComboBox<String> jctipo;
    private javax.swing.JTextField jtarg;
    // End of variables declaration//GEN-END:variables

    private void listarAlunos() {

        try {

            VisitantesDAOConsulta objVisitantesConsulta = new VisitantesDAOConsulta();
            DefaultTableModel model = (DefaultTableModel) jTableTCVisitantes.getModel();
            model.setNumRows(0);

            ArrayList<VisitantesDTO> lista = objVisitantesConsulta.PesquisarVisitantes();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_visitante(),
                    lista.get(num).getNome(),
                    lista.get(num).getCpf(),
                    lista.get(num).getDatanascimento(),
                    lista.get(num).getTelefone(),
                    lista.get(num).getValordiaria()
                });

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Listar Alunos" + erro);
        }

    } // fim do metodo listar alunos

    public void tamanhocolunas() {

        jTableTCVisitantes.getColumnModel().getColumn(0).setMinWidth(100);
        jTableTCVisitantes.getColumnModel().getColumn(1).setMinWidth(250);

    }

}
