package VIEW;

import DAO.AlunoDAO;
import DAO.AlunoDAOExcluir;
import DAO.AlunoDAOPesquisar;
import DTO.AlunosDTO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TelaCadastroAluno extends javax.swing.JInternalFrame {

    int acao;

    AlunosDTO objAlunosDTO = new AlunosDTO(null, null, null, null, null, null, 0, 0, 0, null, null, null);
    AlunoDAOExcluir objExcluirAluno;
    AlunoDAOPesquisar objPesquisarAluno;

    public TelaCadastroAluno() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_CodAluno = new javax.swing.JTextField();
        jTF_Nome = new javax.swing.JTextField();
        jFTF_DataNasc_Aluno = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSexoAluno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jFTF_Contato_Aluno = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_EnderecoAluno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxModalidadeAluno = new javax.swing.JComboBox<>();
        jFTF_ValoraPagar_Aluno = new javax.swing.JFormattedTextField();
        jComboBoxSituacaoAluno = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jFTF_CPF_Aluno = new javax.swing.JFormattedTextField();
        jButtonSalvarAluno = new javax.swing.JButton();
        jButtonEditarAluno = new javax.swing.JButton();
        jButtonSairAluno = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jFTF_DatadoCadastro_Aluno = new javax.swing.JFormattedTextField();
        jButtonExcluirAluno = new javax.swing.JButton();
        jButtonNovoAluno = new javax.swing.JButton();
        jButtonCancelarAluno = new javax.swing.JButton();
        btn_Pesquisar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jFTF_Multa_Aluno = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Aluno");
        setToolTipText("");
        setAlignmentX(500.0F);
        setAlignmentY(100.0F);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Aluno"));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel3.setText("Data de Nascimento:");

        jTF_Nome.setEnabled(false);
        jTF_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_NomeKeyReleased(evt);
            }
        });

        try {
            jFTF_DataNasc_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_DataNasc_Aluno.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel4.setText("Sexo:");

        jComboBoxSexoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Masculino", "Feminino" }));
        jComboBoxSexoAluno.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel5.setText("CPF:");

        try {
            jFTF_Contato_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_Contato_Aluno.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel6.setText("Endereço:");

        jTF_EnderecoAluno.setEnabled(false);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel7.setText("Modalidade e Mensalidades:");

        jLabel9.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel9.setText("Valor a Pagar:");

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel10.setText("Situação:");

        jComboBoxModalidadeAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jComboBoxModalidadeAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Básico", "Premium", "Gympass", "Master Plus" }));
        jComboBoxModalidadeAluno.setEnabled(false);
        jComboBoxModalidadeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModalidadeAlunoActionPerformed(evt);
            }
        });

        try {
            jFTF_ValoraPagar_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_ValoraPagar_Aluno.setEnabled(false);
        jFTF_ValoraPagar_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTF_ValoraPagar_AlunoActionPerformed(evt);
            }
        });

        jComboBoxSituacaoAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jComboBoxSituacaoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Ativo", "Inativo", "Pagamento Pendênte", "Inadimplente" }));
        jComboBoxSituacaoAluno.setEnabled(false);
        jComboBoxSituacaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoAlunoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel11.setText("Contatos:");

        try {
            jFTF_CPF_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_CPF_Aluno.setEnabled(false);
        jFTF_CPF_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTF_CPF_AlunoActionPerformed(evt);
            }
        });

        jButtonSalvarAluno.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalvarAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jButtonSalvarAluno.setText("Salvar");
        jButtonSalvarAluno.setEnabled(false);
        jButtonSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAlunoActionPerformed(evt);
            }
        });

        jButtonEditarAluno.setBackground(new java.awt.Color(0, 255, 0));
        jButtonEditarAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButtonEditarAluno.setText("Editar");
        jButtonEditarAluno.setEnabled(false);
        jButtonEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAlunoActionPerformed(evt);
            }
        });

        jButtonSairAluno.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSairAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButtonSairAluno.setText("Sair");
        jButtonSairAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairAlunoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel12.setText("Data Cadastro:");

        try {
            jFTF_DatadoCadastro_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_DatadoCadastro_Aluno.setEnabled(false);
        jFTF_DatadoCadastro_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTF_DatadoCadastro_AlunoActionPerformed(evt);
            }
        });

        jButtonExcluirAluno.setBackground(new java.awt.Color(204, 204, 204));
        jButtonExcluirAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButtonExcluirAluno.setText("Excluir");
        jButtonExcluirAluno.setEnabled(false);
        jButtonExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirAlunoActionPerformed(evt);
            }
        });

        jButtonNovoAluno.setBackground(new java.awt.Color(0, 0, 255));
        jButtonNovoAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jButtonNovoAluno.setText("Novo");
        jButtonNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoAlunoActionPerformed(evt);
            }
        });

        jButtonCancelarAluno.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCancelarAluno.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jButtonCancelarAluno.setText("Cancelar");
        jButtonCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAlunoActionPerformed(evt);
            }
        });

        btn_Pesquisar.setText("jButton1");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel13.setText("Multa por Atrasos:");

        jFTF_Multa_Aluno.setName("jFTF_Multa_Aluno"); // NOI18N
        jFTF_Multa_Aluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTF_Multa_AlunoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTF_CodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxSituacaoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCancelarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSairAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSalvarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFTF_Multa_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 533, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFTF_CPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSexoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFTF_Contato_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jFTF_DataNasc_Aluno, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jTF_EnderecoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxModalidadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFTF_ValoraPagar_Aluno)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jFTF_DatadoCadastro_Aluno))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTF_CodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTF_CPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTF_Contato_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTF_DataNasc_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_EnderecoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFTF_DatadoCadastro_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFTF_Multa_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFTF_ValoraPagar_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxModalidadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSituacaoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSairAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(291, 291, 291))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(250, 60, 1083, 666);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSituacaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSituacaoAlunoActionPerformed

    private void jButtonSairAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairAlunoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairAlunoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        jFTF_Multa_Aluno.setEnabled(false);

    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoAlunoActionPerformed

        // Metodo para ativar botão Novo
        acao = 1;
        botaonovoaluno();


    }//GEN-LAST:event_jButtonNovoAlunoActionPerformed

    private void jButtonCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAlunoActionPerformed
        // Metodo para ativar botão Cancelar
        botaocancelaraluno();
    }//GEN-LAST:event_jButtonCancelarAlunoActionPerformed

    private void jButtonEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAlunoActionPerformed
        // Metodo para ativar botão Editar
        acao = 2;
        botaoeditaraluno();
    }//GEN-LAST:event_jButtonEditarAlunoActionPerformed

    private void jButtonSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAlunoActionPerformed
        regrasDeCampos();
    }//GEN-LAST:event_jButtonSalvarAlunoActionPerformed

    private void jFTF_CPF_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTF_CPF_AlunoActionPerformed

    }//GEN-LAST:event_jFTF_CPF_AlunoActionPerformed

    private void jButtonExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirAlunoActionPerformed
        excluirAluno();
    }//GEN-LAST:event_jButtonExcluirAlunoActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        pesquisarAluno();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void jTF_NomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_NomeKeyReleased

        jTF_Nome.setText(jTF_Nome.getText().replaceAll("[^a-z | ^A-Z]", "")); // COD PARA NÃO DEIXAR DIGITAR NUMEROS NO CAMPO DE TEXTO

    }//GEN-LAST:event_jTF_NomeKeyReleased

    private void jFTF_ValoraPagar_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTF_ValoraPagar_AlunoActionPerformed


    }//GEN-LAST:event_jFTF_ValoraPagar_AlunoActionPerformed

    private void jComboBoxModalidadeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModalidadeAlunoActionPerformed
        String valorSelecionado = jComboBoxModalidadeAluno.getSelectedItem().toString();

        if (valorSelecionado == "Básico") {
            jFTF_ValoraPagar_Aluno.setText("RS 60.00");
            JOptionPane.showMessageDialog(null, "O valor para o Plano Básico deve ser RS 60,00 ");
            jFTF_ValoraPagar_Aluno.setText("60");
        } else if (valorSelecionado == "Premium") {
            jFTF_ValoraPagar_Aluno.setText("RS 70.00");
            JOptionPane.showMessageDialog(null, "O valor para o Plano Premium deve ser RS 70,00 ");
            jFTF_ValoraPagar_Aluno.setText("70");
        } else if (valorSelecionado == "Gympass") {
            jFTF_ValoraPagar_Aluno.setText("RS 80.00");
            JOptionPane.showMessageDialog(null, "O valor para o Plano Gympass deve ser RS 80,00 ");
            jFTF_ValoraPagar_Aluno.setText("80");
        } else if (valorSelecionado == "Master Plus") {
            jFTF_ValoraPagar_Aluno.setText("RS 90.00");
            JOptionPane.showMessageDialog(null, "O valor para o Plano Master Plus deve ser RS 90,00 ");
            jFTF_ValoraPagar_Aluno.setText("90");
        } else {
            jFTF_ValoraPagar_Aluno.setText("");

        } // FIM DO METODO PLANOS
    }//GEN-LAST:event_jComboBoxModalidadeAlunoActionPerformed

    private void jFTF_DatadoCadastro_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTF_DatadoCadastro_AlunoActionPerformed

    }//GEN-LAST:event_jFTF_DatadoCadastro_AlunoActionPerformed

    private void jFTF_Multa_AlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTF_Multa_AlunoKeyReleased

        jFTF_Multa_Aluno.setText(jFTF_Multa_Aluno.getText().replaceAll("[^0123456789]", "")); // COD PARA NÃO DEIXAR DIGITAR NUMEROS NO CAMPO DE TEXTO


    }//GEN-LAST:event_jFTF_Multa_AlunoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton jButtonCancelarAluno;
    private javax.swing.JButton jButtonEditarAluno;
    private javax.swing.JButton jButtonExcluirAluno;
    private javax.swing.JButton jButtonNovoAluno;
    private javax.swing.JButton jButtonSairAluno;
    private javax.swing.JButton jButtonSalvarAluno;
    private javax.swing.JComboBox<String> jComboBoxModalidadeAluno;
    private javax.swing.JComboBox<String> jComboBoxSexoAluno;
    private javax.swing.JComboBox<String> jComboBoxSituacaoAluno;
    private javax.swing.JFormattedTextField jFTF_CPF_Aluno;
    private javax.swing.JFormattedTextField jFTF_Contato_Aluno;
    private javax.swing.JFormattedTextField jFTF_DataNasc_Aluno;
    private javax.swing.JFormattedTextField jFTF_DatadoCadastro_Aluno;
    private javax.swing.JTextField jFTF_Multa_Aluno;
    private javax.swing.JFormattedTextField jFTF_ValoraPagar_Aluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_CodAluno;
    private javax.swing.JTextField jTF_EnderecoAluno;
    private javax.swing.JTextField jTF_Nome;
    // End of variables declaration//GEN-END:variables

    public void botaonovoaluno() {

        jTF_Nome.setEnabled(true);
        jFTF_CPF_Aluno.setEnabled(true);
        jFTF_Contato_Aluno.setEnabled(true);
        jFTF_DataNasc_Aluno.setEnabled(true);
        jTF_EnderecoAluno.setEnabled(true);
        jFTF_Multa_Aluno.setEnabled(true);
        jTF_CodAluno.setEnabled(false);
        jFTF_DatadoCadastro_Aluno.setEnabled(true);
        jFTF_ValoraPagar_Aluno.setEnabled(true);
        jFTF_Multa_Aluno.setEnabled(true);

        jComboBoxSexoAluno.setEnabled(true);
        jComboBoxModalidadeAluno.setEnabled(true);
        jComboBoxSituacaoAluno.setEnabled(true);

        jButtonEditarAluno.setEnabled(true);
        jButtonSalvarAluno.setEnabled(true);
        jButtonCancelarAluno.setEnabled(true);

        jTF_CodAluno.setText("");
        jTF_Nome.setText("");
        jFTF_CPF_Aluno.setText("");
        jFTF_Contato_Aluno.setText("");
        jFTF_DataNasc_Aluno.setText("");
        jTF_EnderecoAluno.setText("");
        jFTF_DatadoCadastro_Aluno.setText("");
        jFTF_ValoraPagar_Aluno.setText("");
        jFTF_Multa_Aluno.setText("");

    } // fim do metodo Botão_Novo_Aluno!!

    public void botaocancelaraluno() {

        jTF_CodAluno.setText("");
        jTF_Nome.setText("");
        jFTF_CPF_Aluno.setText("");
        jFTF_Multa_Aluno.setText("");
        jFTF_Contato_Aluno.setText("");
        jFTF_DataNasc_Aluno.setText("");
        jTF_EnderecoAluno.setText("");
        jFTF_DatadoCadastro_Aluno.setText("");
        jFTF_ValoraPagar_Aluno.setText("");
        jFTF_Multa_Aluno.setText("");

        jTF_CodAluno.setEnabled(true);
        jTF_Nome.setEnabled(false);
        jFTF_Multa_Aluno.setEnabled(false);
        jFTF_CPF_Aluno.setEnabled(false);
        jFTF_Contato_Aluno.setEnabled(false);
        jFTF_DataNasc_Aluno.setEnabled(false);
        jTF_EnderecoAluno.setEnabled(false);
        jFTF_DatadoCadastro_Aluno.setEnabled(false);
        jFTF_ValoraPagar_Aluno.setEnabled(false);
        jFTF_Multa_Aluno.setEnabled(false);

        jComboBoxSexoAluno.setEnabled(false);
        jComboBoxModalidadeAluno.setEnabled(false);
        jComboBoxSituacaoAluno.setEnabled(false);

        jButtonEditarAluno.setEnabled(false);
        jButtonSalvarAluno.setEnabled(false);
        jButtonCancelarAluno.setEnabled(false);
        jButtonExcluirAluno.setEnabled(false);

    } // fim do metodo botãoCancelarAluno!!

    public void botaoeditaraluno() {
        jTF_CodAluno.setEnabled(false);
        jTF_Nome.setEnabled(true);
        jFTF_CPF_Aluno.setEnabled(true);
        jFTF_Contato_Aluno.setEnabled(true);
        jFTF_DataNasc_Aluno.setEnabled(true);
        jTF_EnderecoAluno.setEnabled(true);
        jFTF_DatadoCadastro_Aluno.setEnabled(true);
        jFTF_ValoraPagar_Aluno.setEnabled(true);
        jFTF_Multa_Aluno.setEnabled(true);

        jComboBoxSexoAluno.setEnabled(true);
        jComboBoxModalidadeAluno.setEnabled(true);
        jComboBoxSituacaoAluno.setEnabled(true);

        jButtonEditarAluno.setEnabled(true);
        jButtonSalvarAluno.setEnabled(true);
        jButtonCancelarAluno.setEnabled(true);
        jButtonExcluirAluno.setEnabled(true);

    } // fim do metodo Botão_Editar_Aluno!!

    public void pesquisarAluno() {

        AlunosDTO objPesquisarAlunoDTO = new AlunosDTO(null, null, null, null, null, null, 0, 0, 0, null, null, null); // instanciar o objeto da class AlunoDAOPesquisa

        if (jTF_CodAluno.getText().equals("")) { // ESSE IF VAI SERVIR PARA QUANDO N TIVER NENHUM CODIGO, ELE CHAMAR A TELA DE CONSULTA

            /// CHAMAR A TELA DE CONSULTA
            TelaConsultaAluno objConsulta = new TelaConsultaAluno(); // INSTACIAR A TELA DESEJADA
            EntradaLogin.jDesktopPane1.add(objConsulta); // Obs o painel tem que ser acesso publib e static para ter acesso e abrir na página
            objConsulta.setVisible(true); // TORNAR A TELA VISIVEL
            EntradaLogin.jDesktopPane1.setComponentZOrder(objConsulta, 0); // COD PARA DEIXAR A TELA QUE FOI CHAMADA EM PRIMEIRO PLANO, E NÃO ATRÁS

        } else { // CASO NÃO ESTEJA VAZIO VAI EXECUTAR OS CÓDIGOS A BAIXO

            objPesquisarAlunoDTO.setId_aluno(Integer.parseInt(jTF_CodAluno.getText())); // linha de codigo serve para pegar o numero ou informação que está dentro do campo

            objPesquisarAluno = new AlunoDAOPesquisar();

            try {

                if (objPesquisarAluno.PesquisarAluno(objPesquisarAlunoDTO)) {
                    if (objPesquisarAlunoDTO != null) {

                        jTF_Nome.setText(objPesquisarAlunoDTO.getNome());
                        jFTF_CPF_Aluno.setText(objPesquisarAlunoDTO.getCpf());
                        jTF_EnderecoAluno.setText(objPesquisarAlunoDTO.getEnd());
                        jFTF_DataNasc_Aluno.setText(objPesquisarAlunoDTO.getDataNascimento());
                        jFTF_Contato_Aluno.setText(objPesquisarAlunoDTO.getTelefone());
                        jComboBoxSexoAluno.setSelectedItem(objPesquisarAlunoDTO.getSexo());
                        jComboBoxModalidadeAluno.addItem(objPesquisarAlunoDTO.getModalidade());
                        jFTF_ValoraPagar_Aluno.setText(Integer.toString(objPesquisarAlunoDTO.getMensalidade())); // linha onde está dando o erro
                        jFTF_DatadoCadastro_Aluno.setText(objPesquisarAlunoDTO.getDatCadastro());
                        jComboBoxSituacaoAluno.setSelectedItem(objPesquisarAlunoDTO.getSituacao());
                        jFTF_Multa_Aluno.setText(Integer.toString(objPesquisarAlunoDTO.getMulta())); // linha onde está dando o erro
                        jButtonEditarAluno.setEnabled(true);

                    }
                }

            } catch (SQLException e) {

                JOptionPane.showMessageDialog(this, "Erro Ao Pesquisar" + e.getMessage());

            }

        }

        /*jTF_Nome.setText(objAlunosDTO.getNome());
        jFTF_CPF_Aluno.setText(objAlunosDTO.getCpf());
        jFTF_Contato_Aluno.setText(objAlunosDTO.getTelefone());
        jFTF_DataNasc_Aluno.setText(objAlunosDTO.getDataNascimento());
        jComboBoxSexoAluno.setSelectedItem(objAlunosDTO.getSexo());
        jTF_EnderecoAluno.setText(objAlunosDTO.getEnd());
        jComboBoxModalidadeAluno.setSelectedItem(objAlunosDTO.getModalidade());
        jFTF_ValoraPagar_Aluno.setText(Integer.toString(objAlunosDTO.getMensalidade())); // linha onde está dando o erro
        jFTF_DatadoCadastro_Aluno.setText(objAlunosDTO.getDatCadastro());
        jComboBoxSituacaoAluno.setSelectedItem(objAlunosDTO.getSituacao());
        jFTF_Multa_Aluno.setText(Integer.toString(objAlunosDTO.getMulta())); // linha onde está dando o erro
        jButtonEditarAluno.setEnabled(true);
         */
    }

    private void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void regrasDeCampos() {

        if (jTF_Nome.getText().isEmpty()) { // codigo para verificar se o campo ta vazio

            JOptionPane.showMessageDialog(null, "Campo Nome obrigatorio");
            jTF_Nome.requestFocus(); // voltar para o campo nome para usuario preencher

        } else if (jFTF_CPF_Aluno.getText().equals("   .   .   -  ")) {

            JOptionPane.showMessageDialog(null, "Campo CPF obrigatorio");
            jFTF_CPF_Aluno.requestFocus();

        } else if (jTF_EnderecoAluno.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Campo Endereço obrigatorio");
            jFTF_CPF_Aluno.requestFocus();

        } else if (jFTF_Contato_Aluno.getText().equals("(  )     -    ")) {

            JOptionPane.showMessageDialog(null, "Campo Contato obrigatorio");
            jFTF_Contato_Aluno.requestFocus();

        } else if (jFTF_DataNasc_Aluno.getText().equals("  /  /    ")) {

            JOptionPane.showMessageDialog(null, "Campo Data Nascimento obrigatorio");
            jFTF_DataNasc_Aluno.requestFocus();

        } else if (jComboBoxSexoAluno.getSelectedItem().equals("Selecione:")) {

            JOptionPane.showMessageDialog(null, "Selecione seu genero");
            jComboBoxSexoAluno.requestFocus();

        } else if (this.jComboBoxModalidadeAluno.equals("Selecione:")) {

            JOptionPane.showMessageDialog(null, "Selecione A Modalidade");
            jComboBoxModalidadeAluno.requestFocus();
            
        }else if (jFTF_ValoraPagar_Aluno.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Digitar o Valor a pagar");
            jFTF_ValoraPagar_Aluno.requestFocus();
 

        } else if (jFTF_DatadoCadastro_Aluno.getText().equals("  /  /    ")) {

            JOptionPane.showMessageDialog(null, "Digitar a data de cadastro");
            jFTF_DatadoCadastro_Aluno.requestFocus();

        } else if (jComboBoxSituacaoAluno.getSelectedItem().equals("Selecione:")) {

            JOptionPane.showMessageDialog(null, "Selecione a situação do funcionário");
            jComboBoxSituacaoAluno.requestFocus();

        } else {

            validarDate();

        }

    } // FIM DA CLASS REGRAS DOS CAMPOS

    public void validarDate() {

        // PROCESSO PARA VALIDAR CAMPO
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();

        Date dataNascimento;
        try {
            dataNascimento = sdf.parse(jFTF_DataNasc_Aluno.getText());

            cal.setTime(dataNascimento);
            cal.add(Calendar.MONTH, 2);

            int year = cal.get(Calendar.YEAR);
            dataNascimento = cal.getTime();

            Date atualData = new Date();
            cal.setTime(atualData);

            int atualYear = cal.get(Calendar.YEAR);
            int idade = atualYear - year;

            if (idade < 10) {

                JOptionPane.showMessageDialog(null, "Idade minima é de 10 anos");

            } else {
                calculaMulta();

            }
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
        }

    } // FIM CLASS VALIDAR DATA

    // PROCESSO PARA VALIDAR CAMPO MULTA
    public void calculaMulta() throws ParseException {
        Calendar dataLimite = Calendar.getInstance();
        dataLimite.add(Calendar.DAY_OF_YEAR, -30);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date dataCadastro;
        dataCadastro = sdf.parse(jFTF_DatadoCadastro_Aluno.getText());

        if (dataLimite.getTime().before(dataCadastro)) {

            jFTF_Multa_Aluno.setText("0");
        } else {

            jFTF_Multa_Aluno.setText("10");
        }
        salvarAlunos();
    }// FIM DO VALIDAR CAMPO MULTA

    @Deprecated
    public void multa() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();
        Double multa = 10.0;
        Date dataCadastro;
        try {
            dataCadastro = sdf.parse(jFTF_DatadoCadastro_Aluno.getText());

            cal.setTime(dataCadastro);
            cal.add(Calendar.MONTH, 2);

            int year = cal.get(Calendar.YEAR);
            dataCadastro = cal.getTime();

            Date atualData = new Date();
            cal.setTime(atualData);

            int atualYear = cal.get(Calendar.YEAR);
            int hoje = atualYear - year / 365;

            if (hoje > 30) {

                JOptionPane.showMessageDialog(null, "Será aplicado multa por atraso de 10% no valor:! + jFTF_Multa_Aluno");

            } else {
                calculaMulta();
            }
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // FIM DA VALIDAÇÃO DO CAMPO MULTA

    public void salvarAlunos() {

        // Metodo para ativar botão Salvar
        int cod;

        objAlunosDTO = new AlunosDTO(null, null, null, null, null, null, 0, 0, 0, null, null, null);
        objAlunosDTO.setNome(jTF_Nome.getText());
        objAlunosDTO.setCpf(jFTF_CPF_Aluno.getText());
        objAlunosDTO.setTelefone(jFTF_Contato_Aluno.getText());
        objAlunosDTO.setDataNascimento(jFTF_DataNasc_Aluno.getText());
        objAlunosDTO.setSexo((String) jComboBoxSexoAluno.getSelectedItem()); // testar se pega as informações selecionada
        objAlunosDTO.setEnd(jTF_EnderecoAluno.getText());
        objAlunosDTO.setModalidade((String) jComboBoxModalidadeAluno.getSelectedItem());  // testar para ver qual ele recebe a informação
        objAlunosDTO.setMensalidade(Integer.parseInt(jFTF_ValoraPagar_Aluno.getText())); // testar para ver se capta o valor float
        objAlunosDTO.setDatCadastro(jFTF_DatadoCadastro_Aluno.getText());
        objAlunosDTO.setSituacao((String) jComboBoxSituacaoAluno.getSelectedItem());
        objAlunosDTO.setMulta(Integer.parseInt(jFTF_Multa_Aluno.getText().trim()));

        try {

            AlunoDAO objAlunosDAO = new AlunoDAO();

            if (acao == 1) {

                cod = objAlunosDAO.Aluno(objAlunosDTO);
                jTF_CodAluno.setText(String.valueOf(cod));
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");

                jTF_CodAluno.setEnabled(true);
                jTF_Nome.setEnabled(false);
                jFTF_CPF_Aluno.setEnabled(false);
                jFTF_Contato_Aluno.setEnabled(false);
                jFTF_DataNasc_Aluno.setEnabled(false);
                jTF_EnderecoAluno.setEnabled(false);
                jFTF_DatadoCadastro_Aluno.setEnabled(false);
                jFTF_ValoraPagar_Aluno.setEnabled(false);
                jFTF_Multa_Aluno.setEnabled(false);

                jComboBoxSexoAluno.setEnabled(false);
                jComboBoxModalidadeAluno.setEnabled(false);
                jComboBoxSituacaoAluno.setEnabled(false);

                jButtonEditarAluno.setEnabled(true);
                jButtonSalvarAluno.setEnabled(false);
                jButtonCancelarAluno.setEnabled(false);
            }

            if (acao == 2) {

                objAlunosDTO.setId_aluno(Integer.parseInt(jTF_CodAluno.getText()));

                if (objAlunosDAO.Editar(objAlunosDTO)) {

                    JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                    jTF_CodAluno.setEnabled(true);
                    jTF_Nome.setEnabled(false);
                    jFTF_CPF_Aluno.setEnabled(false);
                    jFTF_Contato_Aluno.setEnabled(false);
                    jFTF_DataNasc_Aluno.setEnabled(false);
                    jTF_EnderecoAluno.setEnabled(false);
                    jFTF_DatadoCadastro_Aluno.setEnabled(false);
                    jFTF_ValoraPagar_Aluno.setEnabled(false);
                    jFTF_Multa_Aluno.setEnabled(false);

                    jComboBoxSexoAluno.setEnabled(false);
                    jComboBoxModalidadeAluno.setEnabled(false);
                    jComboBoxSituacaoAluno.setEnabled(false);

                    jButtonEditarAluno.setEnabled(true);
                    jButtonSalvarAluno.setEnabled(false);
                    jButtonCancelarAluno.setEnabled(false);

                }

                //fechar conexao - DEPOIS VERIFICAR ESSE METODO
                /*
                ConexaoDAO con = new ConexaoDAO();
                con.getConexaoFechar();
                 */
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Operação deu erro" + erro.getMessage());
        }

    } // FIM DO METODO SALVAR ALUNO 

    public void excluirAluno() {

        if (jTF_CodAluno.getText().equals("")) {  //  ESSE IF VAI SER PARA FAZER UMA VERIFICAÇÃO, SE TEM CODIGO OU NÃO..

            JOptionPane.showMessageDialog(this, "Digite o Código");

        } else { // SE TIVER CODIGO VAI FAZER A SEGUINTE OPERAÇÃO

            int codigo = Integer.parseInt(jTF_CodAluno.getText());  // ESSA VARIVEL VAI CARREGAR OS VALORES DO CAMPO CITADO.
            objExcluirAluno = new AlunoDAOExcluir(); // codigo para instanciar o objeto

            try {

                if (JOptionPane.showConfirmDialog(this, "Confirma a exclusão do Aluno?", "Confirmação",
                        JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) { // codigo para da 3 opções ao usuario, sim, não e cancelar
                    // codigo a cima vai ser muito utilizado para perguntar algo ao usuario
                    if (objExcluirAluno.ExcluirAluno(codigo)) { // se a caixa for respondida com sim, ele vai retornar a mensagem a baixo e executar.
                        JOptionPane.showMessageDialog(this, "Excluido com sucesso !");
                        botaocancelaraluno();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir o registro");
                    }
                } else {

                    JOptionPane.showMessageDialog(this, "Operação Cancelada !");
                    botaocancelaraluno();

                }

            } catch (SQLException erro) {
                JOptionPane.showMessageDialog(this, "Erro: Exclusão Não Realizada" + erro.getMessage());
            }

        }

    } // FIM DO METODO EXCLUIR ALUNO

}// fim da classe principal
